version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    hostname: es01
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - 9200:9200
    networks:
      - trino-ranger-demo
    volumes:
    - ranger-es-data:/usr/share/elasticsearch/data
  postgresql:
    image: postgres:13
    container_name: psql01
    hostname: psql01
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - trino-ranger-demo
    volumes:
    - ranger-pg-data:/var/lib/postgresql/data
  ranger-admin:
    image: trino-ranger-demo:v3.0
    container_name: ranger-admin
    hostname: ranger-admin
    entrypoint: /root/docker-entrypoint.sh
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 5G
    ports:
      - 6080:6080
    networks:
      - trino-ranger-demo
    volumes:
      - ./ranger-admin/install.properties:/root/install.properties
      - ./ranger-admin/docker-entrypoint.sh:/root/docker-entrypoint.sh
  trino:
    image: trinodb/trino:384
    hostname: my-localhost-trino
    user: root
    container_name: my-localhost-trino
    entrypoint: /root/docker-entrypoint.sh
    networks:
      - trino-ranger-demo
    volumes:
      - ./trino/install.properties:/root/install.properties
      - ./trino/docker-entrypoint.sh:/root/docker-entrypoint.sh
    ports:
      - 8080:8080
networks:
  trino-ranger-demo:
    driver: bridge
volumes:
  ranger-es-data:
  ranger-pg-data:
